# Generated by Django 5.2 on 2025-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
